# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python application
on:
  workflow_dispatch:
  schedule:
  - cron:  '0 23 * * *'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        date
        sudo timedatectl set-timezone "Etc/GMT+8"
        date
    #     python -m pip install --upgrade pip
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - shell: bash
    #   env:
    #     SUPER_SECRET: ${{ secrets.CONFIG_FILE }}
    #   run: |
    #     echo "$SUPER_SECRET" > config.json
    # - name: Test with pytest
    #   run: |
    #     python ./main.py
